### ISSUE TITLE
Generating eclipse project using catkin tools

### ISSUE THREAD

**Issue by tcies** [ethz-asl/programming_guidelines#18]
How do you do it? If I do

```
catkin build --merge-devel --force-cmake --cmake-args -G"Eclipse CDT4 - Unix Makefiles"
```

I get:

```
[nlopt] ==> '/home/titus/catkin_ws/build/nlopt/build_env.sh /usr/bin/cmake /home/titus/catkin_ws/src/nlopt -DCATKIN_DEVEL_PREFIX=/home/titus/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/titus/catkin_ws/install -GEclipse CDT4 - Unix Makefiles' in '/home/titus/catkin_ws/build/nlopt'
CMake Error: Could not create named generator Eclipse
[nlopt] <== '/home/titus/catkin_ws/build/nlopt/build_env.sh /usr/bin/cmake /home/titus/catkin_ws/src/nlopt -DCATKIN_DEVEL_PREFIX=/home/titus/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/titus/catkin_ws/install -GEclipse CDT4 - Unix Makefiles' failed with return code '1'
```

Probably due to:
http://stackoverflow.com/questions/16073040/call-cmake-from-python-script-results-in-could-not-create-named-generator

I currently found a workaround by:

```
cd build
cmake ../src/ -DCATKIN_DEVEL_SPACE=../devel -DCMAKE_INSTALL_PREFIX=../install -G"Eclipse CDT4 - Unix Makefiles"
```

As inspired by:
http://catkin-tools.readthedocs.org/en/latest/commands/catkin_build.html?highlight=cmake#understanding-the-build-process

**Comment by cyborg-x1** [comment]
What about debuging? I sourced .bashrc_additions like that

> bash -c 'source /home/cyborg-x1/.bash_additions; $pathtoeclipse/eclipse"

I created this file because of the "interactivity"-check  which is normal for the bashrc.
To run/debug I searched for the file in devel and added it.
Running works fine so far but on debug I get:
> No source available for "main() at 0x409f96" 

(In that package I have two nodes btw)
Am I missing something?

**Comment by HannesSommer** [comment]
Did you double check that you compiled your executable with debug symbols (-g) ? (For cmake this is typically achieved with ```CMAKE_BUILD_TYPE=Debug``` or similar. See http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html)

**Comment by cyborg-x1** [comment]
Where exactly shall I put this in eclipse?
I tried the builder settings but it did not do anything there.
